[project]
name = "digiwill"
authors = []
description = ""
telemetry = true
requirements = []
analysis = ["check_checker"]
costs_version = 2
[contracts.digital]
path = "contracts/digital.clar"
depends_on = []
